## Import Libraries

In [2]:
import pandas as pd 
import numpy as np
import seaborn as sns 
import matplotlib.pyplot as plt

## Load Dataset

In [3]:
df = pd.read_csv("cleaned_amazon.csv")

## Data Cleaning

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 661 entries, 0 to 660
Data columns (total 7 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Title            661 non-null    object
 1   ratings          661 non-null    float64
 2   total_reviews    661 non-null    int64
 3   buying_history   661 non-null    object
 4   alinknormal_URL  661 non-null    object
 5   Price            661 non-null    float64
 6   Image            661 non-null    object
dtypes: float64(2), int64(1), object(4)
memory usage: 36.3+ KB

In [5]:
df.isnull().sum()

Title              0
ratings            0
total_reviews      0
buying_history     0
alinknormal_URL    0
Price              0
Image              0
dtype: int64

In [6]:
df.head()

,Title,ratings,total_reviews,buying_history,alinknormal_URL,Price,Image
0,Plant-Based Kitchen Sponges - FSC Certified an...,4.6,248,3K+ bought in past month,https://www.amazon.com/Isshah-Plant-Based-Kitc...,9.99,https://m.media-amazon.com/images/I/81GEZUgvk2...
1,Reusable Paper Towels Washable Roll - Thick 12...,4.6,205,100+ bought in past month,https://www.amazon.com/EcoPledge-Reusable-Pape...,24.99,https://m.media-amazon.com/images/I/91-W1NYNeY...
2,20 Pack Reusable Paper Towels Washable - Natur...,4.4,3274,900+ bought in past month,https://www.amazon.com/Reusable-Alternative-Wa...,31.94,https://m.media-amazon.com/images/I/81WV3GCPce...
3,Akeeko Reusable Beeswax Food Wraps - Assorted ...,4.4,2426,50+ bought in past month,https://www.amazon.com/Reusable-Wraps-Beeswax-...,13.99,https://m.media-amazon.com/images/I/91UpDUvsk-...
4,Swedish Dishcloths for Kitchen Dish Towels - 6...,4.6,1286,100+ bought in past month,https://www.amazon.com/Harps-Seb-Reusable-Swed...,13.90,https://m.media-amazon.com/images/I/91FngmRdt1...

In [7]:
categorial_cols = df.select_dtypes(include="object").columns

for col in categorial_cols:
    print("\n---",col,"---")
    print(df[col].value_counts().head(20))

--- Title ---
Title
Reusable Beeswax Wrap - 9 Pack Beeswax Wraps For Food, Organic, Sustainable, Biodegradable, Zero Waste, Plastic-Free Food Storage, 1L Strawberry, 3M Orange, 5S Lemon Patterns                            6
Tieralia 5-Piece Eco-Friendly Bamboo Dish Brush Set with Compostable Wood Pulp Sponges | Bamboo Kitchen Cleaning Set                                                                                      6
Plant-Based Kitchen Sponges - FSC Certified and PETA Approved, Natural, Eco-Friendly, Biodegradable Sisal Hemp Sponges for Dishes, Cleaning Sponge for Kitchen, Bathroom, Household - 12 Count            6
Bamboo Cutting Board, Durable Wood Cutting Boards for Kitchen with Deep Juice Grooves & Built-in Handles, Ideal Charcuterie & Chopping for Meat, Vegetables - Perfect Kitchen Gift for Home Cooks         5
Natural Kitchen Sponge - Biodegradable Compostable Cellulose and Coconut Scrubber Sponge - Pack of 12 Eco Friendly Sponges for Dishes                                                                     5
Zero Waste Natural Dish Soap Bar (Pack of 3 Bars) - Solid Vegan Dishwashing Block - Cold Processed, Eco Friendly Plastic Free Packaging with Sustainable Organic Ingredients for Kitchen                  4
| Premium Natural Kitchen Sponge | Non Scratch | Long Lasting | Waste Free | Compostable Sponge Kitchen | Natural Fiber | Eco-Friendly | Eartch Friendly | Vegan | 6 Pack                                 4
UNNI Compostable Liner Bags, 2.6 Gallon, 9.84 Liter, Extra Thick 0.71 Mil, 100 Count, Small Kitchen Food Scrap Waste Bags, ASTM D6400, US BPI, CMA and Europe OK compost HOME Certified, San Francisco    4
20 Pack Reusable Paper Towels Washable - Nature Friendly - Organic Cotton Alternative - Thick, Strong, Paperless Kitchen Dish Cloths - Reusable Napkins - Dish Towels - Cloth Napkin - Kitchen Towels     3
Akeeko Reusable Beeswax Food Wraps - Assorted 9 Packs, Eco-Friendly Reusable Wrap, Biodegradable, Zero Waste, Organic Cloth, Sustainable, Plastic-Free Food Storage, 1Large, 3Medium, 5Small Sizes        3
6 Layer Fleece Duster Refills for Swiffer Hand Duster, Zero Waste, Reusable and Washable Replacement Dusters for Cleaning Ceiling Fan Hardwoods (6 Pack-Multicolour-A)                                    3
Biodegradable Natural Kitchen Sponge，Eco Friendly Sponges for Dishes,Compostable Cellulose Sponge with Natural Plant Based Coconut Walnut Sustainable Scrubber Sponge Pack of 12                          3
Reusable Paper Towels Washable Roll - Thick 12-pc Two Layered Ultra Absorbent Paperless Certified Organic Cotton Towels - Large Cloth Kitchen Paper Towel with Hanging Loop                               3
Bamboo Facial Tissues - 12 Boxes of Eco-Friendly, 3-Ply Hypoallergenic Tissues, 90 Sheets per Box, FSC Certified, Plastic-Free Packaging, Soft & Gentle for Home Use                                      3
10 Pack Biodegradable Natural Sponges Kitchen - Compostable Cellulose and Coconut Walnut Scrubber Sponge - Eco Friendly Sponges for Dishes                                                                3
eplanita Natural Dish Brush, 3 Replacement Heads, Kitchen Eco Bamboo Scrubber Brushes, Extra Plant Sponge, Plastic Free Washing Up, Zero Waste Cleaning                                                   3
Jungle Culture® 6 Piece Natural Dish Brushes for Washing Up • Eco Dish Brush Kitchen Cleaning Set • Plant Based Coconut Scrubbers • Bottle/Pot Brush & Eco Friendly Scourer Sponge for Pans & Dishes      3
Compostable Bags for Kitchen Compost Bin, 1.2 Gallon, 125 Count, Certified by BPI and ASTM, Leakproof and Odor Control                                                                                    3
9 Pack Biodegradable Natural Kitchen Sponge - Compostable Cellulose and Coconut Walnut Scrubber Sponge - Eco Friendly Sustainable Sponges for Dishes                                                      3
HOBIBEAR Barefoot Minimalist Shoes Womens Mens | Zero Drop | Wide Width Fashion Sneaker                                                                                                                   3
Name: count, dtype: int64

--- buying_history ---
buying_history
50+ bought in past month     288
1K+ bought in past month      61
100+ bought in past month     52
200+ bought in past month     44
2K+ bought in past month      28
500+ bought in past month     26
300+ bought in past month     22
4K+ bought in past month      20
10K+ bought in past month     20
600+ bought in past month     18
3K+ bought in past month      16
400+ bought in past month     15
5K+ bought in past month      13
900+ bought in past month      9
700+ bought in past month      9
800+ bought in past month      5
20K+ bought in past month      4
9K+ bought in past month       4
6K+ bought in past month       3
8K+ bought in past month       2
Name: count, dtype: int64

--- alinknormal_URL ---
alinknormal_URL
https://www.amazon.com/s?k=sustainable+clothing#                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 12
https://www.amazon.com/s?k=eco+friendly+fashion#                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 12
https://www.amazon.com/s?k=organic+cotton+clothing#                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              12
https://www.amazon.com/s?k=sustainable+home+goods#                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               10
https://www.amazon.com/s?k=bamboo+home+products#                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 10
https://www.amazon.com/s?k=sustainable+kitchen+products#                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          9
https://www.amazon.com/s?k=compostable+home+products#                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             9
https://www.amazon.com/s?k=biodegradable+kitchen+products#                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        9
https://www.amazon.com/s?k=zero+waste+kitchen#                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    9
https://www.amazon.com/s?k=plastic+free+kitchen#                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  9
https://www.amazon.com/s?k=sustainable+shoes#                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     9
https://www.amazon.com/s?k=eco+friendly+kitchen+utensils#                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         7
https://www.amazon.com/s?k=ethical+fashion#                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       4
https://www.amazon.com/Compostable-Biodegradable-Dog-Poop-Bags/dp/B08GKBWFGZ/ref=sr_1_33?dib=eyJ2IjoiMSJ9.F8hMRDQGLTNnJld1eHE6MdYJSCQqbvu6_mb5vK62tS_GYGF_uDGYBuU7d86CRm-ghR0-eiigtWB6jxCjFGi-Of3VZvSmNrsT4SdkmKOZVk03Tv5gOOthIjpOERm_ssk60RmK1KzYiWBlUTVk5sjk0XAZmQXB2QCqnsDikOuz5Y4ksbqGkT1jYobI2USxAo_PkhwiSQoZTcssaOdM52XDR-uejCjAOKeDXhtjTiqaRsz_t550HvZx-57FbzBqSj1mywJXYFeJA-w_ppYrDl1M7rV29or67f27LUEz3lKO2XjH-RsK36-trcRpAToo3ERaElpXzsPbFbfn7_KeiynXpz1TvqVMYrp5Zk-RlncGtVc2P59Re0cZUijW-TIo7uY-TQuU3dDm92QO1VlOYcVKm3BD5qoWCjXF5bVDPrYuf6TSEs2zwqgEzjE8QyB9pKng.hPglgJ-D6mYAwa64aLfUngEd7Cjio8hsHE5VxgP-pe4&dib_tag=se&keywords=eco+friendly+home+products&qid=1741331887&sr=8-33                      1
https://www.amazon.com/KITHELP-Reusable-Leak-proof-Sandwich-Eco-Friendly/dp/B088GP2W83/ref=sr_1_11?dib=eyJ2IjoiMSJ9.F8hMRDQGLTNnJld1eHE6MdYJSCQqbvu6_mb5vK62tS_GYGF_uDGYBuU7d86CRm-ghR0-eiigtWB6jxCjFGi-Of3VZvSmNrsT4SdkmKOZVk03Tv5gOOthIjpOERm_ssk60RmK1KzYiWBlUTVk5sjk0XAZmQXB2QCqnsDikOuz5Y4ksbqGkT1jYobI2USxAo_PkhwiSQoZTcssaOdM52XDR-uejCjAOKeDXhtjTiqaRsz_t550HvZx-57FbzBqSj1mywJXYFeJA-w_ppYrDl1M7rV29or67f27LUEz3lKO2XjH-RsK36-trcRpAToo3ERaElpXzsPbFbfn7_KeiynXpz1TvqVMYrp5Zk-RlncGtVc2P59Re0cZUijW-TIo7uY-TQuU3dDm92QO1VlOYcVKm3BD5qoWCjXF5bVDPrYuf6TSEs2zwqgEzjE8QyB9pKng.hPglgJ-D6mYAwa64aLfUngEd7Cjio8hsHE5VxgP-pe4&dib_tag=se&keywords=eco+friendly+home+products&qid=1741331887&sr=8-11            1
https://www.amazon.com/MoLKENE-Swedish-Dish-Cloths-Dishcloths/dp/B0B9S9SJQB/ref=sr_1_12?dib=eyJ2IjoiMSJ9.F8hMRDQGLTNnJld1eHE6MdYJSCQqbvu6_mb5vK62tS_GYGF_uDGYBuU7d86CRm-ghR0-eiigtWB6jxCjFGi-Of3VZvSmNrsT4SdkmKOZVk03Tv5gOOthIjpOERm_ssk60RmK1KzYiWBlUTVk5sjk0XAZmQXB2QCqnsDikOuz5Y4ksbqGkT1jYobI2USxAo_PkhwiSQoZTcssaOdM52XDR-uejCjAOKeDXhtjTiqaRsz_t550HvZx-57FbzBqSj1mywJXYFeJA-w_ppYrDl1M7rV29or67f27LUEz3lKO2XjH-RsK36-trcRpAToo3ERaElpXzsPbFbfn7_KeiynXpz1TvqVMYrp5Zk-RlncGtVc2P59Re0cZUijW-TIo7uY-TQuU3dDm92QO1VlOYcVKm3BD5qoWCjXF5bVDPrYuf6TSEs2zwqgEzjE8QyB9pKng.hPglgJ-D6mYAwa64aLfUngEd7Cjio8hsHE5VxgP-pe4&dib_tag=se&keywords=eco+friendly+home+products&qid=1741331887&sr=8-12                       1
https://www.amazon.com/Candle-Hour-80-Hour-Vertical-Eco-friendly/dp/B000LWRZNM/ref=sr_1_13?dib=eyJ2IjoiMSJ9.F8hMRDQGLTNnJld1eHE6MdYJSCQqbvu6_mb5vK62tS_GYGF_uDGYBuU7d86CRm-ghR0-eiigtWB6jxCjFGi-Of3VZvSmNrsT4SdkmKOZVk03Tv5gOOthIjpOERm_ssk60RmK1KzYiWBlUTVk5sjk0XAZmQXB2QCqnsDikOuz5Y4ksbqGkT1jYobI2USxAo_PkhwiSQoZTcssaOdM52XDR-uejCjAOKeDXhtjTiqaRsz_t550HvZx-57FbzBqSj1mywJXYFeJA-w_ppYrDl1M7rV29or67f27LUEz3lKO2XjH-RsK36-trcRpAToo3ERaElpXzsPbFbfn7_KeiynXpz1TvqVMYrp5Zk-RlncGtVc2P59Re0cZUijW-TIo7uY-TQuU3dDm92QO1VlOYcVKm3BD5qoWCjXF5bVDPrYuf6TSEs2zwqgEzjE8QyB9pKng.hPglgJ-D6mYAwa64aLfUngEd7Cjio8hsHE5VxgP-pe4&dib_tag=se&keywords=eco+friendly+home+products&qid=1741331887&sr=8-13                    1
https://www.amazon.com/Kitsch-Spray-Bottle-Hair-Hairstyling/dp/B0CVZWMD34/ref=sr_1_14?dib=eyJ2IjoiMSJ9.F8hMRDQGLTNnJld1eHE6MdYJSCQqbvu6_mb5vK62tS_GYGF_uDGYBuU7d86CRm-ghR0-eiigtWB6jxCjFGi-Of3VZvSmNrsT4SdkmKOZVk03Tv5gOOthIjpOERm_ssk60RmK1KzYiWBlUTVk5sjk0XAZmQXB2QCqnsDikOuz5Y4ksbqGkT1jYobI2USxAo_PkhwiSQoZTcssaOdM52XDR-uejCjAOKeDXhtjTiqaRsz_t550HvZx-57FbzBqSj1mywJXYFeJA-w_ppYrDl1M7rV29or67f27LUEz3lKO2XjH-RsK36-trcRpAToo3ERaElpXzsPbFbfn7_KeiynXpz1TvqVMYrp5Zk-RlncGtVc2P59Re0cZUijW-TIo7uY-TQuU3dDm92QO1VlOYcVKm3BD5qoWCjXF5bVDPrYuf6TSEs2zwqgEzjE8QyB9pKng.hPglgJ-D6mYAwa64aLfUngEd7Cjio8hsHE5VxgP-pe4&dib_tag=se&keywords=eco+friendly+home+products&qid=1741331887&sr=8-14                         1
https://www.amazon.com/Cutting-Durable-Charcuterie-Chopping-Vegetables/dp/B0D7M8QB9Y/ref=sr_1_15?dib=eyJ2IjoiMSJ9.F8hMRDQGLTNnJld1eHE6MdYJSCQqbvu6_mb5vK62tS_GYGF_uDGYBuU7d86CRm-ghR0-eiigtWB6jxCjFGi-Of3VZvSmNrsT4SdkmKOZVk03Tv5gOOthIjpOERm_ssk60RmK1KzYiWBlUTVk5sjk0XAZmQXB2QCqnsDikOuz5Y4ksbqGkT1jYobI2USxAo_PkhwiSQoZTcssaOdM52XDR-uejCjAOKeDXhtjTiqaRsz_t550HvZx-57FbzBqSj1mywJXYFeJA-w_ppYrDl1M7rV29or67f27LUEz3lKO2XjH-RsK36-trcRpAToo3ERaElpXzsPbFbfn7_KeiynXpz1TvqVMYrp5Zk-RlncGtVc2P59Re0cZUijW-TIo7uY-TQuU3dDm92QO1VlOYcVKm3BD5qoWCjXF5bVDPrYuf6TSEs2zwqgEzjE8QyB9pKng.hPglgJ-D6mYAwa64aLfUngEd7Cjio8hsHE5VxgP-pe4&dib_tag=se&keywords=eco+friendly+home+products&qid=1741331887&sr=8-15              1
https://www.amazon.com/Reusable-Washable-Replacement-Hardwoods-Pack-Multicolour/dp/B0CMLNRVT3/ref=sr_1_16?dib=eyJ2IjoiMSJ9.F8hMRDQGLTNnJld1eHE6MdYJSCQqbvu6_mb5vK62tS_GYGF_uDGYBuU7d86CRm-ghR0-eiigtWB6jxCjFGi-Of3VZvSmNrsT4SdkmKOZVk03Tv5gOOthIjpOERm_ssk60RmK1KzYiWBlUTVk5sjk0XAZmQXB2QCqnsDikOuz5Y4ksbqGkT1jYobI2USxAo_PkhwiSQoZTcssaOdM52XDR-uejCjAOKeDXhtjTiqaRsz_t550HvZx-57FbzBqSj1mywJXYFeJA-w_ppYrDl1M7rV29or67f27LUEz3lKO2XjH-RsK36-trcRpAToo3ERaElpXzsPbFbfn7_KeiynXpz1TvqVMYrp5Zk-RlncGtVc2P59Re0cZUijW-TIo7uY-TQuU3dDm92QO1VlOYcVKm3BD5qoWCjXF5bVDPrYuf6TSEs2zwqgEzjE8QyB9pKng.hPglgJ-D6mYAwa64aLfUngEd7Cjio8hsHE5VxgP-pe4&dib_tag=se&keywords=eco+friendly+home+products&qid=1741331887&sr=8-16     1
Name: count, dtype: int64

--- Image ---
Image
https://m.media-amazon.com/images/I/910pb+R-1UL._AC_UL320_.jpg    7
https://m.media-amazon.com/images/I/81GEZUgvk2L._AC_UL320_.jpg    6
https://m.media-amazon.com/images/I/81-cLbynG7L._AC_UL320_.jpg    6
https://m.media-amazon.com/images/I/81rF0i715fL._AC_UL320_.jpg    5
https://m.media-amazon.com/images/I/71g+Afy5T9L._AC_UL320_.jpg    5
https://m.media-amazon.com/images/I/91zidZ1V1VL._AC_UL320_.jpg    5
https://m.media-amazon.com/images/I/91UpDUvsk-L._AC_UL320_.jpg    4
https://m.media-amazon.com/images/I/71ybUvPV3nL._AC_UL320_.jpg    4
https://m.media-amazon.com/images/I/713GeQ-ieZL._AC_UL320_.jpg    4
https://m.media-amazon.com/images/I/71AC1L+FAwL._AC_UL320_.jpg    3
https://m.media-amazon.com/images/I/91874WFeyaL._AC_UL320_.jpg    3
https://m.media-amazon.com/images/I/91-W1NYNeYL._AC_UL320_.jpg    3
https://m.media-amazon.com/images/I/81WV3GCPceL._AC_UL320_.jpg    3
https://m.media-amazon.com/images/I/71et3onJIqL._AC_UL320_.jpg    3
https://m.media-amazon.com/images/I/81FBh8uXs-L._AC_UL320_.jpg    3
https://m.media-amazon.com/images/I/913AlyfjIcL._AC_UL320_.jpg    3
https://m.media-amazon.com/images/I/81IgJVlQomL._AC_UL320_.jpg    3

In [8]:
numerical_cols = df.select_dtypes(include=np.number).columns
print(numerical_cols.tolist())

['ratings', 'total_reviews', 'Price']

In [9]:
df_analysis = df.copy()

In [10]:
df_analysis["product_text"] = (
    df_analysis['Title']
    .fillna("")
    .astype(str)
    .str.lower()
)

## Sustainability Keyword Detection

In [19]:
sustainability_keywords = {
    "strong": [
        "biodegradable",
        "compostable",
        "zero waste",
        "plastic-free",
        "plastic free",
        "reusable"
    ],

    "medium": [
        "sustainable",
        "eco-friendly",
        "eco friendly",
        "organic",
        "plant-based",
        "plant based",
        "fsc certified",
        "bpi certified",
        "certified compostable",
        "ethical",
        "ethics",
        "slow fashion",
        "fair trade",
        "fairtrade",
        "responsibly made",
        "environmentally friendly",
        "enviroment friendly"
    ],

    "supporting": [
        "bamboo",
        "natural",
        "vegan",
        "washable",
        "recyclable",
    ]
}

In [12]:
keyword_weights = {
    "strong":3,
    "medium":2,
    "supporting":1
}

In [20]:
def find_sustainability_keywords(text):
    found = []
    
    for category, keywords in sustainability_keywords.items():
        for keyword in keywords:
            if keyword in text:
                found.append(keyword)
    
    return found

In [21]:
df_analysis["Found_Keywords"] = (
    df_analysis["product_text"]
    .apply(find_sustainability_keywords)
)

In [22]:
df_analysis[
    ["Title","Found_Keywords"]
].head(10)

,Title,Found_Keywords
0,Plant-Based Kitchen Sponges - FSC Certified an...,"[biodegradable, eco-friendly, plant-based, fsc..."
1,Reusable Paper Towels Washable Roll - Thick 12...,"[reusable, organic, washable]"
2,20 Pack Reusable Paper Towels Washable - Natur...,"[reusable, organic, washable]"
3,Akeeko Reusable Beeswax Food Wraps - Assorted ...,"[biodegradable, zero waste, plastic-free, reus..."
4,Swedish Dishcloths for Kitchen Dish Towels - 6...,"[biodegradable, reusable, washable]"
5,"Lucomb Swedish Dishcloths for Kitchen Dishes, ...","[biodegradable, reusable, eco friendly]"
6,Reusable Beeswax Wrap - 9 Pack Beeswax Wraps F...,"[biodegradable, zero waste, plastic-free, reus..."
7,100% Compostable Food Storage Bags [Quart 100 ...,"[compostable, reusable, eco-friendly, natural]"
8,Tieralia 5-Piece Eco-Friendly Bamboo Dish Brus...,"[compostable, eco-friendly, bamboo]"
9,Ultrasonic Pest Control Repeller - Repel Roden...,[eco-friendly]

In [27]:
def calculate_sustainability_score(text):
    score = 0
    for category, keywords in sustainability_keywords.items():
        for keyword in keywords:
            if keyword in text:
                score += keyword_weights[category]

    return score

## Sustainability Score

In [28]:
df_analysis["Sustainability_Score"] = (
    df_analysis["product_text"]
    .apply(calculate_sustainability_score)
)

In [29]:
df_analysis[
    ["Title","Found_Keywords","Sustainability_Score"]
].head(10)

,Title,Found_Keywords,Sustainability_Score
0,Plant-Based Kitchen Sponges - FSC Certified an...,"[biodegradable, eco-friendly, plant-based, fsc...",10
1,Reusable Paper Towels Washable Roll - Thick 12...,"[reusable, organic, washable]",6
2,20 Pack Reusable Paper Towels Washable - Natur...,"[reusable, organic, washable]",6
3,Akeeko Reusable Beeswax Food Wraps - Assorted ...,"[biodegradable, zero waste, plastic-free, reus...",18
4,Swedish Dishcloths for Kitchen Dish Towels - 6...,"[biodegradable, reusable, washable]",7
5,"Lucomb Swedish Dishcloths for Kitchen Dishes, ...","[biodegradable, reusable, eco friendly]",8
6,Reusable Beeswax Wrap - 9 Pack Beeswax Wraps F...,"[biodegradable, zero waste, plastic-free, reus...",16
7,100% Compostable Food Storage Bags [Quart 100 ...,"[compostable, reusable, eco-friendly, natural]",9
8,Tieralia 5-Piece Eco-Friendly Bamboo Dish Brus...,"[compostable, eco-friendly, bamboo]",6
9,Ultrasonic Pest Control Repeller - Repel Roden...,[eco-friendly],2

## Sustainability Evidence Level

In [32]:
def classify_sustainability(score):
    if score <=2:
        return "Low"
    elif score <= 5:
        return "Moderate"
    else:
        return "Strong"

df_analysis["Sustainability_Evidence_Level"]=(
    df_analysis["Sustainability_Score"]
    .apply(classify_sustainability)
)

In [33]:
df_analysis["Sustainability_Evidence_Level"].value_counts()

Sustainability_Evidence_Level
Low         349
Strong      166
Moderate    146
Name: count, dtype: int64

In [34]:
df_analysis["Sustainability_Score"].value_counts().sort_index()

Sustainability_Score
0     199
1      57
2      93
3      85
4      20
5      41
6      37
7      29
8      19
9      24
10     22
11      7
12      2
13      3
14     10
15      2
16      6
17      1
18      4
Name: count, dtype: int64

In [35]:
df_analysis["Found_Keywords"] =(
    df_analysis["product_text"]
    .apply(find_sustainability_keywords)
)

df_analysis["Sustainability_Score"] = (
    df_analysis["product_text"]
    .apply(calculate_sustainability_score)
)

df_analysis["Sustainability_Evidence_Level"] =(
    df_analysis["Sustainability_Score"]
    .apply(classify_sustainability)
)

In [36]:
df_analysis["Sustainability_Evidence_Level"].value_counts()

Sustainability_Evidence_Level
Low         349
Strong      166
Moderate    146
Name: count, dtype: int64

In [38]:
non_product_keywords = [
    "boook",
    "dummies",
    "handbook",
    "guide",
    "fashion ethics",
    "ethics",
    "how to",
    "history of",
    "the art of",
    "magazine"
]

def detect_non_product(title):
    title = str(title).lower()

    for keyword in non_product_keywords:
        if keyword in title:
            return "Possible Non-Product"
    return "Likely Product"
df_analysis["Product_Type"] = (
    df_analysis["Title"]
    .apply(detect_non_product)
)

In [39]:
df_analysis["Product_Type"].value_counts()

Product_Type
Likely Product          641
Possible Non-Product     20
Name: count, dtype: int64

In [40]:
df_analysis[
    df_analysis["Product_Type"] == "Possible Non-Product"
][
    ["Title","Sustainability_Score","Sustainability_Evidence_Level"]
].head(10)

,Title,Sustainability_Score,Sustainability_Evidence_Level
218,Waste-Free Kitchen Handbook: A Guide to Eating...,5,Moderate
281,40 Projects for Building Your Backyard Homeste...,2,Low
283,Simply Living Well: A Guide to Creating a Natu...,1,Low
284,Sustainable Badass: A Zero-Waste Lifestyle Gui...,4,Moderate
290,"Green from the Ground Up: Sustainable, Healthy...",2,Low
293,The Organic Country Home Handbook: How to Make...,2,Low
297,Zero Waste Home: The Ultimate Guide to Simplif...,3,Moderate
303,"Never Home Alone: From Microbes to Millipedes,...",1,Low
314,Back to Basics: A Complete Guide to Traditiona...,0,Low
316,"New Good Food Pocket Guide, rev: Shopper's Poc...",4,Moderate

In [41]:
df_analysis[
    df_analysis["Product_Type"] == "Possible Non-Product"
][
    ["Title","Sustainability_Score","Sustainability_Evidence_Level"]
]

,Title,Sustainability_Score,Sustainability_Evidence_Level
218,Waste-Free Kitchen Handbook: A Guide to Eating...,5,Moderate
281,40 Projects for Building Your Backyard Homeste...,2,Low
283,Simply Living Well: A Guide to Creating a Natu...,1,Low
284,Sustainable Badass: A Zero-Waste Lifestyle Gui...,4,Moderate
290,"Green from the Ground Up: Sustainable, Healthy...",2,Low
293,The Organic Country Home Handbook: How to Make...,2,Low
297,Zero Waste Home: The Ultimate Guide to Simplif...,3,Moderate
303,"Never Home Alone: From Microbes to Millipedes,...",1,Low
314,Back to Basics: A Complete Guide to Traditiona...,0,Low
316,"New Good Food Pocket Guide, rev: Shopper's Poc...",4,Moderate
516,The Secrets Of Upcycled Fashions: How To Turn ...,2,Low
518,Sustainable Fashion for Dummies,2,Low
535,Fix Your Fashion: How to Create an Ethical War...,2,Low
549,Mending Life: A Handbook for Repairing Clothes...,2,Low
599,The Art of Ethical Fashion: A stunning glimpse...,2,Low
601,The Fashion Industry Doesn't Want You To Read ...,4,Moderate
605,Slow Fashion: Aesthetics Meets Ethics,4,Moderate
607,How To Break Up With Fast Fashion: A guilt-fre...,0,Low
608,Why We Can't Have Nice Things: Social Media’s ...,2,Low
612,Fashion Ethics,2,Low

## Sustainability Category

In [48]:
def classify_sustainability(row):
    score = row['Sustainability_Score']
    evidence = str(row['Sustainability_Evidence_Level']).strip().lower()

    if evidence == 'strong' and score >=6:
        return "Sustainable"
    elif(evidence == 'moderate' and score >=3) or (evidence == 'strong' and score < 6):
        return "Potentially Sustainable"
    else:
        return "Not Sustainable"
df_analysis["Sustainability_Category"] = df_analysis.apply(classify_sustainability, axis=1)

print(df_analysis[['Title',
         'Sustainability_Score',
         'Sustainability_Evidence_Level',
         'Sustainability_Category']].head(20))

                                                Title  Sustainability_Score  \
0   Plant-Based Kitchen Sponges - FSC Certified an...                    10
1   Reusable Paper Towels Washable Roll - Thick 12...                     6
2   20 Pack Reusable Paper Towels Washable - Natur...                     6
3   Akeeko Reusable Beeswax Food Wraps - Assorted ...                    18
4   Swedish Dishcloths for Kitchen Dish Towels - 6...                     7
5   Lucomb Swedish Dishcloths for Kitchen Dishes, ...                     8
6   Reusable Beeswax Wrap - 9 Pack Beeswax Wraps F...                    16
7   100% Compostable Food Storage Bags [Quart 100 ...                     9
8   Tieralia 5-Piece Eco-Friendly Bamboo Dish Brus...                     6
9   Ultrasonic Pest Control Repeller - Repel Roden...                     2
10  21 Pack Reusable Storage Bags BPA Free, Leak-p...                     6
11  Swedish Dish Cloths - 10 Pack Reusable Kitchen...                     3
12  Candle by the Hour 80-Hour Vertical Candle, Ec...                     3
13  Kitsch Spray Bottle for Hair - Continuous Wate...                     0
14  Bamboo Cutting Board, Durable Wood Cutting Boa...                     1
15  6 Layer Fleece Duster Refills for Swiffer Hand...                     7
16  Stardrops – The Pink Stuff – Miracle Microfibr...                     0
17  Bamboo Facial Tissues - 12 Boxes of Eco-Friend...                     8
18  Biodegradable Silk Dental Floss with Refillabl...                    12
19  Bee's Wrap Reusable Vegan Alternative to Beesw...                    10

   Sustainability_Evidence_Level  Sustainability_Category
0                         Strong              Sustainable
1                         Strong              Sustainable
2                         Strong              Sustainable
3                         Strong              Sustainable
4                         Strong              Sustainable
5                         Strong              Sustainable
6                         Strong              Sustainable
7                         Strong              Sustainable
8                         Strong              Sustainable
9                            Low          Not Sustainable
10                        Strong              Sustainable
11                      Moderate  Potentially Sustainable
12                      Moderate  Potentially Sustainable
13                           Low          Not Sustainable
14                           Low          Not Sustainable
15                        Strong              Sustainable
16                           Low          Not Sustainable
17                        Strong              Sustainable
18                        Strong              Sustainable
19                        Strong              Sustainable

In [49]:
print(df_analysis['Sustainability_Category'].value_counts())
print("\nPercentage:")
print(
    df_analysis['Sustainability_Category'].value_counts(normalize=True).mul(100).round(2)
)

Sustainability_Category
Not Sustainable            349
Sustainable                166
Potentially Sustainable    146
Name: count, dtype: int64

Percentage:
Sustainability_Category
Not Sustainable            52.80
Sustainable                25.11
Potentially Sustainable    22.09
Name: proportion, dtype: float64

## Price Vs Sustainability Analysis

In [55]:
price_analysis = df_analysis.groupby('Sustainability_Category')['Price'].agg(['count','mean','median','min','max']).round(2)
print(price_analysis)

                         count   mean  median   min     max
Sustainability_Category
Not Sustainable            349  20.39   16.99  2.23  289.99
Potentially Sustainable    146  21.74   18.58  1.97   88.99
Sustainable                166  18.12   14.99  5.49   59.95

In [56]:
correlation = df_analysis['Price'].corr(df_analysis['Sustainability_Score'])
print("Price vs Sustainability Score Correlation:", round(correlation, 3))

Price vs Sustainability Score Correlation: -0.075

## Export Dataset

In [54]:
df_analysis.to_csv("Sustainable_Shopping_Analysis_Final.csv", index=False)